### ISSUE TITLE
[Meta] Programme de parrainage

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#250]
Pour booster l’acquisition de nouveaux participants, nous pourrons compter sur quelques leviers externes (communication interne du Wagon) mais nous pourrions créer des incitations directement sur la plateforme : un **programme de parrainage**.

## Principe

Le principe serait de créer une sorte de leaderboard pré-calendrier, sur la période entre l'ouverture des inscriptions et le 1er décembre. Chaque utilisateur inscrit aurait un code/lien de parrainage qu'il pourra partager sur Slack, et chaque inscrit utilisant son code lui rapporte des "points".

Le gagnant remporterait un lot symbolique, de la "vanity" cosmétique comme un pseudo d'une couleur différente ou un GIF dans le pseudo. En tout cas, quelque chose qu'on maîtrise nous. Des achievements 💡 

## Design

À l'inscription, chaque utilisateur obtient un code unique de parrainage (exemple : `MFND4E`).
Depuis son compte, il peut partager son lien de parrainage, que j'imagine de la forme : 
```
https://aoc.lewagon.community/?friend=MFND4E
```
Lorsqu'un utilisateur clique sur ce lien alors qu'il n'est pas inscrit, il se retrouve sur la page d'accueil, avec ce paramètre. S'il clique sur "Sign In", avec ce paramètre, alors l'utilisateur est considéré comme inscrit via le code `MFND4E`.

### Leaderboard

Une page dédiée permet de voir en temps réel le leaderboard des parrains.
Ce leaderboard sera figé au Lock Time (environ 1 semaine après le 1er décembre).

```
username | referrals | aura
```

L'`aura` est un score qui a pour formule :  
```
100 * (
  ln(1 + total_referrals)
  + 2 * ln(1 + referrals_with_1_completion)
  + 3 * ln(1 + referrals_with_2_completions)
  + 5 * ln(1 + referrals_with_3_completions_or_more)
)
```

Cette formule récompense bien sûr le nombre de filleuls, mais surtout leur engagement (= font-ils les puzzles ?) sur le début de l'événement.
Dans l'idée, ces utilisateurs auront la même `aura` :
* 1 filleul qui résout 3+ puzzles
* 3 filleuls qui résolvent chacun un seul puzzle
* 63 filleuls mais aucun n'a résolu de puzzle

**Comment by wJoenn** [comment]
Est ce qu'on utiliserait pas une colonne qui existe deja pour le lien de parainage comme le pseudo Github, l'uid ou l'id AoC ?
Je suis pour l'idée. Ca serait assez rapide a mettre en place avec une reference du parrain sur le user. Les points du coup ca pourrait simplement etre  `user.sponsored.count` * un nombre au choix si tu veux rendre le tout un peu plus grandiose

**Comment by wJoenn** [comment]
Quelle difference entre  `User.where(referrer: self.uid).count` et `self.sponsored.count` ?

**Comment by wJoenn** [comment]
```ruby
class User
  belong_to :sponsor, class_name: "User", optional: true
  has_many :sponsored, class_name: "User", inverse_of: sponsor
end
```

**Comment by Aquaj** [comment]
**Côté produit:**
Est-ce qu'on est sûr de vouloir prendre cette direction en mode growth ? Ça peut peut-être être détrimental à l'ambiance de gonfler le nombre d'user de façon "artificielle" comme ça, non ? (Je suis pas convaincu que ça le sera, mais juste qu'on explore l'idée pour être sûrs de notre coup).

**Côté tech:** 
Pas hyper complexe à mettre en place.
Peut-être la première version peut être plus "stupide": plutôt qu'un lien juste un code à saisir dans le process d'inscription directement. 
Ça nous évite d'avoir à gérer les edge-cases genre "je clique sur le lien mais je suis déjà inscrit" (gérer un early-return en cas de login) / "j'ai cliqué sur le lien mais après j'ai changé de page avant de m'inscrire et ça a perdu le params et du coup je suis inscrit sans parrain" (cookie à mettre en place pour track) / etc. 
Quitte à itérer après pour arriver au niveau d'expérience qui nous va.

**Comment by Aquaj** [comment]
> je suis optimiste en me disant qu'il ne manquera pas grand chose pour avoir un lien

Complètement, mais ça nous permet d'y aller progressivement si jamais on se rend compte que c'est une galère à faire proprement 😄

**Comment by wJoenn** [comment]
J'voudrais diviser la tache en plusieurs PR pour accelerer le processus de review.
Dans un premier temps ca serait de creer le systeme en back.

- [ ] ajouter une reference `recruiter` sur `users` et une colonne `recruit_url`
- [ ] Dans le User model `has_many :recruited` et `belongs_to :recruiter, optional: true`
- [ ] `after_create :add_recruit_url` avec `SecureRandom.urlsafe_base64`
- [ ] ajouter une methode dans `PagesController#welcome` pour récuperer le params dans l'url et le stocker en cookie
- [ ] a la creation du user, recuperer le cookie, trouver le parrain et l'assigné comme `recruiter`
- [ ] supprimer le cookie une fois le user creer
- [ ] dans la methode qui stock l'url en cookie, ajouter une guard clause qui return si la date est après le 10 decembre

Ensuite pour le front
- [ ] ajouter un bouton dans les settings pour copier son lien de parainage
- [ ] afficher ses filleuls sur son profil, sous forme de tableau avec le score de chacun par exemple ?
- [ ] ajouter une page `recruit a friend` pour afficher le leaderboard des parrains
- [ ] Pour le scoring faisons simple, 1 point par filleul avec un `User.recruited.count`
- [ ] Ajouter une question dans la FAQ pour mentionner le parrainage
- [ ] Ajouter une mention du parrainage dans setup
- [ ] Ajouter une stat sur le nombre de filleuls recruter ?
