### ISSUE TITLE
Communication to-do list

### ISSUE THREAD

**Issue by pil0u** [pil0u/lewagon-aoc#71]
## Communication

- [x] Touch base with Ursula, the new E&C Paris
- [x] Touch base with French E&Cs 
- [x] Every city in the world is aware of the event ([Google Slides](https://docs.google.com/presentation/d/11qwFepYK-4rT_g8L8iFXHQuypMV4oEbcCfzRybXswlk/edit?usp=sharing))
- [x] We have a video trailer

## Prizes

- [x] Send a message to Guillaume directly
- [x] More small prizes for more people (100 t-shirts, 20 virtual escape rooms for squads, 1000€ for a party) => 5700€

## Adventofcode.com

- [x] Get an answer from Eric about larger private leaderboards (it's a no)

**Comment by pil0u** [comment]
## Prizes

Solo cheating is driven by high cash prizes. Drastically reducing the incentives would drive cheating down.
* Small prizes for solo casual ranking (e.g. top 25 get a prize)
* Small prizes for the squads (e.g. top 3)
* Symbolic prize for the best city

**Comment by pil0u** [comment]
## Video teaser

This kind of music: https://morninglightmusic.io/music/fear/ ([source](https://www.youtube.com/watch?v=WQmGwmc-XUY))
Before...
- People with 5.55am alarm
- People working on their laptop
- People hiding from their boss to code
- BOOM / People frustrated with code
- People looking on their ranking, focusing on the one person above
- Bruxels winner of 2021 edition
- The stats page with numbers increasing (sign ups, stars...)
Then
- 2022 / LE WAGON x ADVENT OF CODE IS BACK
- WITH NEW FEATURES
- flashes of SQUAD SYSTEM / ACHIEVEMENTS / THE WALL / final boom NEW PUZZLES ON DECEMBER 1ST
- SIGN UP on aoc/lewagon.community

Release Thursday November 17th, the 2022 platform opens at the same time.

**Comment by pil0u** [comment]
Lamiaa has left Le Wagon, new contact is Ursula.
